package ops

import (
	"bufio"
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"math"

	"github.com/gravity-zero/mkvgo/ebml"
	"github.com/gravity-zero/mkvgo/mkv"
	"github.com/gravity-zero/mkvgo/mkv/writer"
)

// errUnknownSizeCluster is returned by reindexFastCopy when the first cluster
// has an unknown (streaming) size. EditMetadata catches this and falls back to
// streamToWriter before any cluster data has been written to the output.
var errUnknownSizeCluster = errors.New("reindex: unknown-size cluster, falling back to streamToWriter")

const (
	reindexBufSize        = 256 * 1024 // 256 KB sequential read buffer
	reindexCueMinGapMs    = 500        // mirrors mkvwriter.go minCueIntervalMs
	maxReindexClusterSize = 256 << 20  // 256 MB: largest sane cluster; guards against OOM on crafted input
)

// reindexFastCopy copies every cluster from srcPath verbatim into mw,
// rebuilding the Cues index by scanning each cluster body in-memory (one
// io.ReadFull per cluster, no per-block allocations).
//
// When progress is non-nil and totalBytes > 0, it is called after each cluster
// with (bytesConsumed, totalBytes). bytesConsumed is the logical byte offset
// within the source file (sum of all element headers + bodies processed so far).
//
// Precondition: mw.WriteStart() and mw.WriteMetadata() have been called.
// Postcondition: caller must call mw.Finalize().
func reindexFastCopy(mw *writer.MKVWriter, srcPath string, timecodeScale int64, fs *mkv.FS, progress mkv.ProgressFunc, totalBytes int64) error {
	raw, err := fs.DoOpen(srcPath)
	if err != nil {
		return fmt.Errorf("reindex open: %w", err)
	}
	defer raw.Close()

	// Wrap in a bufio.Reader for efficient sequential reads.
	r := bufio.NewReaderSize(raw, reindexBufSize)

	// Mirror BlockReader.init(): skip EBML header body, land on Segment data.
	ebmlHdr, ebmlHdrBytes, err := ebml.ReadElementHeader(r)
	if err != nil {
		return fmt.Errorf("reindex: EBML header: %w", err)
	}
	if ebmlHdr.ID != ebml.IDEBMLHeader {
		return fmt.Errorf("reindex: expected EBML header, got 0x%X", ebmlHdr.ID)
	}
	if _, err := io.CopyN(io.Discard, r, ebmlHdr.Size); err != nil {
		return fmt.Errorf("reindex: skip EBML header: %w", err)
	}

	segHdr, segHdrBytes, err := ebml.ReadElementHeader(r)
	if err != nil {
		return fmt.Errorf("reindex: Segment header: %w", err)
	}
	if segHdr.ID != mkv.IDSegment {
		return fmt.Errorf("reindex: expected Segment, got 0x%X", segHdr.ID)
	}
	// We do not need segEnd: unknown-size segment reads until EOF, known-size
	// segments also terminate naturally (their clusters fill them).

	// Track logical bytes consumed for progress reporting.
	consumed := int64(ebmlHdrBytes) + ebmlHdr.Size + int64(segHdrBytes)

	var (
		clusterBuf   []byte // reused; grown as needed
		firstCluster = true
	)

	for {
		h, hdrBytes, err := ebml.ReadElementHeader(r)
		if err != nil {
			if errors.Is(err, io.EOF) {
				return nil
			}
			return fmt.Errorf("reindex: top-level element: %w", err)
		}

		switch h.ID {
		case mkv.IDCluster:
			if h.Size < 0 {
				// Unknown-size cluster: can only fall back at the very first cluster.
				if firstCluster {
					return errUnknownSizeCluster
				}
				return fmt.Errorf("reindex: unknown-size cluster after first (streaming not supported)")
			}
			if h.Size > maxReindexClusterSize {
				return fmt.Errorf("reindex: cluster size %d exceeds limit (%d)", h.Size, maxReindexClusterSize)
			}
			firstCluster = false

			// Grow reusable buffer once.
			if int(h.Size) > len(clusterBuf) {
				clusterBuf = make([]byte, h.Size)
			}
			body := clusterBuf[:h.Size]
			if _, err := io.ReadFull(r, body); err != nil {
				return fmt.Errorf("reindex: read cluster body: %w", err)
			}
			consumed += int64(hdrBytes) + h.Size

			// Capture output offset BEFORE writing — this is the ClusterPos.
			outOff := mw.RelPos()

			// Scan cluster body to produce a cue entry.
			appendCueFromCluster(mw, body, timecodeScale, outOff)

			// Write cluster header + verbatim body.
			if _, err := ebml.WriteElementID(mw.W, mkv.IDCluster); err != nil {
				return fmt.Errorf("reindex: write cluster ID: %w", err)
			}
			if _, err := ebml.WriteDataSize(mw.W, h.Size); err != nil {
				return fmt.Errorf("reindex: write cluster size: %w", err)
			}
			if _, err := mw.W.Write(body); err != nil {
				return fmt.Errorf("reindex: write cluster body: %w", err)
			}

			if progress != nil && totalBytes > 0 {
				progress(consumed, totalBytes)
			}

		default:
			// SeekHead, Cues, Void, Info, Tracks, Chapters, Attachments, Tags —
			// all regenerated by WriteMetadata / Finalize; skip the source copy.
			if h.Size < 0 {
				return fmt.Errorf("reindex: unknown-size non-cluster element 0x%X", h.ID)
			}
			if _, err := io.CopyN(io.Discard, r, h.Size); err != nil {
				return fmt.Errorf("reindex: skip 0x%X: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size
		}
	}
}

// appendCueFromCluster scans the raw bytes of a cluster body to find the first
// keyframe and adds a CuePoint to mw.Cues. outOff is the output-relative byte
// offset of this cluster's element header (to store in CuePoint.ClusterPos).
//
// Errors inside the scan are silently ignored (corrupt/truncated data): in the
// worst case we emit no cue for this cluster, which is safe.
func appendCueFromCluster(mw *writer.MKVWriter, body []byte, timecodeScale, outOff int64) {
	br := bytes.NewReader(body)

	var clusterTS int64
	// firstBlock* captures the very first block seen (used for audio-only cue).
	var firstBlockTC int64
	var firstBlockTrack uint64
	var firstBlockSeen bool

	for {
		h, _, err := ebml.ReadElementHeader(br)
		if err != nil {
			break // EOF or corrupt — stop scanning
		}

		switch h.ID {
		case mkv.IDTimestamp:
			v, err := ebml.ReadUint(br, h.Size)
			if err != nil {
				return
			}
			clusterTS = int64(v)

		case mkv.IDSimpleBlock:
			track, relTC, keyframe, err := readBlockHeader(br, h.Size)
			if err != nil {
				return
			}
			tc, err := reindexSafeTimecodeMs(clusterTS+int64(relTC), timecodeScale)
			if err != nil {
				return
			}
			if !firstBlockSeen {
				firstBlockSeen = true
				firstBlockTC = tc
				firstBlockTrack = track
			}
			if keyframe {
				// Found first keyframe — emit cue and exit.
				mw.Cues = append(mw.Cues, mkv.CuePoint{
					TimeMs:     tc,
					Track:      track,
					ClusterPos: outOff,
				})
				return
			}

		case mkv.IDBlockGroup:
			track, relTC, isKey, err := scanBlockGroup(br, h.Size)
			if err != nil {
				return
			}
			tc, err := reindexSafeTimecodeMs(clusterTS+int64(relTC), timecodeScale)
			if err != nil {
				return
			}
			if !firstBlockSeen {
				firstBlockSeen = true
				firstBlockTC = tc
				firstBlockTrack = track
			}
			if isKey {
				mw.Cues = append(mw.Cues, mkv.CuePoint{
					TimeMs:     tc,
					Track:      track,
					ClusterPos: outOff,
				})
				return
			}

		default:
			if h.Size < 0 {
				return // unknown-size child — stop scanning
			}
			if _, err := io.CopyN(io.Discard, br, h.Size); err != nil {
				return
			}
		}
	}

	// No keyframe found (audio-only): throttle to 1 cue per reindexCueMinGapMs.
	if !firstBlockSeen {
		return
	}
	lastCueTime := int64(-reindexCueMinGapMs - 1)
	if len(mw.Cues) > 0 {
		lastCueTime = mw.Cues[len(mw.Cues)-1].TimeMs
	}
	if firstBlockTC-lastCueTime >= reindexCueMinGapMs {
		mw.Cues = append(mw.Cues, mkv.CuePoint{
			TimeMs:     firstBlockTC,
			Track:      firstBlockTrack,
			ClusterPos: outOff,
		})
	}
}

// readBlockHeader reads the fixed block header (track VINT + 2-byte relTC +
// 1-byte flags) and discards the remaining payload bytes.
// Returns (track, relTC, keyframe).
func readBlockHeader(r io.Reader, blockSize int64) (track uint64, relTC int16, keyframe bool, err error) {
	trackRaw, n, err := ebml.ReadDataSize(r)
	if err != nil {
		return 0, 0, false, err
	}
	track = uint64(trackRaw)
	consumed := int64(n)

	var tcBuf [2]byte
	if _, err := io.ReadFull(r, tcBuf[:]); err != nil {
		return 0, 0, false, err
	}
	relTC = int16(binary.BigEndian.Uint16(tcBuf[:]))
	consumed += 2

	var flagBuf [1]byte
	if _, err := io.ReadFull(r, flagBuf[:]); err != nil {
		return 0, 0, false, err
	}
	keyframe = flagBuf[0]&0x80 != 0
	consumed += 1

	remaining := blockSize - consumed
	if remaining > 0 {
		if _, err := io.CopyN(io.Discard, r, remaining); err != nil {
			return track, relTC, keyframe, err
		}
	}
	return track, relTC, keyframe, nil
}

// scanBlockGroup scans a BlockGroup's children to find the Block element and
// detect whether a ReferenceBlock is present (its presence means non-keyframe).
// Consumes exactly size bytes from r.
func scanBlockGroup(r io.Reader, size int64) (track uint64, relTC int16, isKeyframe bool, err error) {
	limit := &io.LimitedReader{R: r, N: size}
	var foundBlock bool
	var hasRef bool

	for {
		h, _, err := ebml.ReadElementHeader(limit)
		if err != nil {
			break
		}
		switch h.ID {
		case mkv.IDBlock:
			t, rt, _, e := readBlockHeader(limit, h.Size)
			if e != nil {
				// Drain and report error.
				io.CopyN(io.Discard, limit, limit.N) //nolint:errcheck
				return 0, 0, false, e
			}
			track = t
			relTC = rt
			foundBlock = true
		case mkv.IDReferenceBlock:
			hasRef = true
			io.CopyN(io.Discard, limit, h.Size) //nolint:errcheck
		default:
			if h.Size >= 0 {
				io.CopyN(io.Discard, limit, h.Size) //nolint:errcheck
			}
		}
	}
	// Drain any unconsumed bytes (e.g. unknown-size child stopped iteration).
	if limit.N > 0 {
		io.CopyN(io.Discard, limit, limit.N) //nolint:errcheck
	}
	if !foundBlock {
		return 0, 0, false, fmt.Errorf("BlockGroup without Block element")
	}
	return track, relTC, !hasRef, nil
}

// reindexSafeTimecodeMs converts raw timecode units to milliseconds,
// mirroring the unexported reader.safeTimecodeMs to avoid an import cycle.
func reindexSafeTimecodeMs(v, scale int64) (int64, error) {
	if scale != 0 && (v > math.MaxInt64/scale || v < math.MinInt64/scale) {
		return 0, fmt.Errorf("timecode overflow: %d * %d", v, scale)
	}
	return v * scale / 1_000_000, nil
}

// writeClusterVerbatim writes one cluster (header + body) to mw, appends a cue
// point, and reports progress. body must be the complete cluster body already
// read from the source. outOff is mw.RelPos() captured before this call.
func writeClusterVerbatim(mw *writer.MKVWriter, body []byte, bodySize int64, timecodeScale, outOff int64) error {
	appendCueFromCluster(mw, body, timecodeScale, outOff)
	if _, err := ebml.WriteElementID(mw.W, mkv.IDCluster); err != nil {
		return fmt.Errorf("reindex: write cluster ID: %w", err)
	}
	if _, err := ebml.WriteDataSize(mw.W, bodySize); err != nil {
		return fmt.Errorf("reindex: write cluster size: %w", err)
	}
	if _, err := mw.W.Write(body); err != nil {
		return fmt.Errorf("reindex: write cluster body: %w", err)
	}
	return nil
}

// Reindex produces a byte-faithful copy of srcPath at dstPath, replacing only
// the seek index (SeekHead + Cues). Every other element — Info, Tracks, Tags,
// Chapters, Attachments, cluster payloads — is copied verbatim, byte for byte,
// without re-serialisation. The source's EBML header is also copied verbatim so
// that the DocType (e.g. "webm") is preserved.
//
// Use this instead of EditMetadata when the only goal is to add a seek index to
// a file that lacks one or has a stale one, and fidelity to the original
// metadata encoding matters.
func Reindex(ctx context.Context, srcPath, dstPath string, opts ...mkv.Options) error {
	fs := mkv.FSFrom(opts)
	progress := mkv.ProgressFrom(opts)

	raw, err := fs.DoOpen(srcPath)
	if err != nil {
		return fmt.Errorf("reindex open src: %w", err)
	}
	defer raw.Close()

	out, err := fs.DoCreate(dstPath)
	if err != nil {
		return fmt.Errorf("reindex create dst: %w", err)
	}
	defer out.Close()

	r := bufio.NewReaderSize(raw, reindexBufSize)
	mw := writer.NewMKVWriter(out)

	// ── EBML header ──────────────────────────────────────────────────────────
	// Read the source EBML header and copy it verbatim so DocType is preserved.
	ebmlHdr, _, err := ebml.ReadElementHeader(r)
	if err != nil {
		return fmt.Errorf("reindex: read EBML header: %w", err)
	}
	if ebmlHdr.ID != ebml.IDEBMLHeader {
		return fmt.Errorf("reindex: expected EBML header, got 0x%X", ebmlHdr.ID)
	}
	if ebmlHdr.Size < 0 {
		return fmt.Errorf("reindex: EBML header has unknown size")
	}
	ebmlBody := make([]byte, ebmlHdr.Size)
	if _, err := io.ReadFull(r, ebmlBody); err != nil {
		return fmt.Errorf("reindex: read EBML body: %w", err)
	}
	// Write the EBML element verbatim: ID header + body.
	if _, err := ebml.WriteElementID(out, ebmlHdr.ID); err != nil {
		return fmt.Errorf("reindex: write EBML ID: %w", err)
	}
	if _, err := ebml.WriteDataSize(out, ebmlHdr.Size); err != nil {
		return fmt.Errorf("reindex: write EBML size: %w", err)
	}
	if _, err := out.Write(ebmlBody); err != nil {
		return fmt.Errorf("reindex: write EBML body: %w", err)
	}

	// ── Segment ───────────────────────────────────────────────────────────────
	// Read source Segment header (we don't need its size; we write unknown-size).
	segHdr, _, err := ebml.ReadElementHeader(r)
	if err != nil {
		return fmt.Errorf("reindex: read Segment header: %w", err)
	}
	if segHdr.ID != mkv.IDSegment {
		return fmt.Errorf("reindex: expected Segment, got 0x%X", segHdr.ID)
	}
	// Emit a new Segment with unknown size (same as MKVWriter.WriteStart does).
	if _, err := ebml.WriteElementID(out, mkv.IDSegment); err != nil {
		return fmt.Errorf("reindex: write Segment ID: %w", err)
	}
	if _, err := ebml.WriteDataSize(out, -1); err != nil {
		return fmt.Errorf("reindex: write Segment size: %w", err)
	}
	// Record where segment data starts (needed for RelPos() arithmetic).
	segDataStart, err := out.Seek(0, io.SeekCurrent)
	if err != nil {
		return fmt.Errorf("reindex: seek Segment data start: %w", err)
	}
	mw.SegDataStart = segDataStart
	mw.SeekHeadPos = 0 // will be filled at the front
	if err := writer.WriteVoid(out, writer.SeekHeadReserve); err != nil {
		return fmt.Errorf("reindex: write SeekHead placeholder: %w", err)
	}

	// ── Walk source Segment elements ──────────────────────────────────────────
	var (
		clusterBuf    []byte
		firstCluster  = true
		consumed      int64
		timecodeScale int64 = 1_000_000 // default; overridden when Info is copied
	)

	var totalBytes int64
	if progress != nil {
		if stat, _ := fs.DoStat(srcPath); stat != nil {
			totalBytes = stat.Size()
		}
	}

	for {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		h, hdrBytes, err := ebml.ReadElementHeader(r)
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return fmt.Errorf("reindex: top-level element: %w", err)
		}

		switch h.ID {
		case mkv.IDSeekHead, mkv.IDCues, mkv.IDVoid:
			// Drop old index elements — they will be rebuilt by Finalize.
			if h.Size < 0 {
				return fmt.Errorf("reindex: unknown-size index element 0x%X", h.ID)
			}
			if _, err := io.CopyN(io.Discard, r, h.Size); err != nil {
				return fmt.Errorf("reindex: skip 0x%X: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size

		case mkv.IDInfo, mkv.IDTracks, mkv.IDTags, mkv.IDChapters, mkv.IDAttachments:
			// Copy verbatim; record position so Finalize's SeekHead points here.
			if h.Size < 0 {
				return fmt.Errorf("reindex: unknown-size metadata element 0x%X", h.ID)
			}
			// Buffer the body so we can (a) scan Info for timecodeScale and
			// (b) write it out verbatim in one step.
			metaBuf := make([]byte, h.Size)
			if _, err := io.ReadFull(r, metaBuf); err != nil {
				return fmt.Errorf("reindex: read 0x%X body: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size
			// Extract timecodeScale from Info before writing.
			if h.ID == mkv.IDInfo {
				if ts := reindexScanTimecodeScale(metaBuf); ts > 0 {
					timecodeScale = ts
				}
				mw.TimecodeScale = timecodeScale
			}
			pos := mw.RelPos()
			switch h.ID {
			case mkv.IDInfo:
				mw.InfoPos = pos
			case mkv.IDTracks:
				mw.TracksPos = pos
			case mkv.IDTags:
				mw.TagsPos = pos
			case mkv.IDChapters:
				mw.ChaptersPos = pos
			case mkv.IDAttachments:
				mw.AttachPos = pos
			}
			// Write element header (same ID, same size) then verbatim body.
			if _, err := ebml.WriteElementID(out, h.ID); err != nil {
				return fmt.Errorf("reindex: write 0x%X ID: %w", h.ID, err)
			}
			if _, err := ebml.WriteDataSize(out, h.Size); err != nil {
				return fmt.Errorf("reindex: write 0x%X size: %w", h.ID, err)
			}
			if _, err := out.Write(metaBuf); err != nil {
				return fmt.Errorf("reindex: write 0x%X body: %w", h.ID, err)
			}

		case mkv.IDCluster:
			if h.Size < 0 {
				if firstCluster {
					return fmt.Errorf("reindex: unknown-size cluster (streaming not supported)")
				}
				return fmt.Errorf("reindex: unknown-size cluster after first")
			}
			if h.Size > maxReindexClusterSize {
				return fmt.Errorf("reindex: cluster size %d exceeds limit (%d)", h.Size, maxReindexClusterSize)
			}
			firstCluster = false

			if int(h.Size) > len(clusterBuf) {
				clusterBuf = make([]byte, h.Size)
			}
			body := clusterBuf[:h.Size]
			if _, err := io.ReadFull(r, body); err != nil {
				return fmt.Errorf("reindex: read cluster body: %w", err)
			}
			consumed += int64(hdrBytes) + h.Size

			outOff := mw.RelPos()
			if err := writeClusterVerbatim(mw, body, h.Size, timecodeScale, outOff); err != nil {
				return err
			}

			if progress != nil && totalBytes > 0 {
				progress(consumed, totalBytes)
			}

		default:
			// Unknown top-level element: copy verbatim to preserve any extensions.
			if h.Size < 0 {
				return fmt.Errorf("reindex: unknown-size element 0x%X", h.ID)
			}
			if _, err := ebml.WriteElementID(out, h.ID); err != nil {
				return fmt.Errorf("reindex: write unknown 0x%X ID: %w", h.ID, err)
			}
			if _, err := ebml.WriteDataSize(out, h.Size); err != nil {
				return fmt.Errorf("reindex: write unknown 0x%X size: %w", h.ID, err)
			}
			if _, err := io.CopyN(out, r, h.Size); err != nil {
				return fmt.Errorf("reindex: copy unknown 0x%X body: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size
		}
	}

	return mw.Finalize()
}

// reindexScanTimecodeScale scans the raw bytes of an Info element body for the
// IDTimecodeScale child element and returns its value. Returns 0 if not found
// or on any parse error (caller keeps the default 1_000_000).
func reindexScanTimecodeScale(body []byte) int64 {
	br := bytes.NewReader(body)
	for {
		h, _, err := ebml.ReadElementHeader(br)
		if err != nil {
			return 0
		}
		if h.ID == mkv.IDTimecodeScale {
			v, err := ebml.ReadUint(br, h.Size)
			if err != nil {
				return 0
			}
			return int64(v)
		}
		if h.Size < 0 {
			return 0
		}
		if _, err := io.CopyN(io.Discard, br, h.Size); err != nil {
			return 0
		}
	}
}
