package ops

import (
	"bufio"
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"hash/crc32"
	"io"
	"math"
	"sort"

	"github.com/gravity-zero/mkvgo/ebml"
	"github.com/gravity-zero/mkvgo/mkv"
	"github.com/gravity-zero/mkvgo/mkv/reader"
	"github.com/gravity-zero/mkvgo/mkv/writer"
)

// errUnknownSizeCluster is returned by reindexFastCopy when the first cluster
// has an unknown (streaming) size. EditMetadata catches this and falls back to
// streamToWriter before any cluster data has been written to the output.
var errUnknownSizeCluster = errors.New("reindex: unknown-size cluster, falling back to streamToWriter")

const (
	reindexBufSize        = 256 * 1024 // 256 KB sequential read buffer
	reindexCueMinGapMs    = 500        // mirrors mkvwriter.go minCueIntervalMs
	maxReindexClusterSize = 256 << 20  // 256 MB: largest sane cluster; guards against OOM on crafted input
)

// reindexFastCopy copies every cluster from srcPath verbatim into mw,
// rebuilding the Cues index by scanning each cluster body in-memory (one
// io.ReadFull per cluster, no per-block allocations).
//
// When progress is non-nil and totalBytes > 0, it is called after each cluster
// with (bytesConsumed, totalBytes). bytesConsumed is the logical byte offset
// within the source file (sum of all element headers + bodies processed so far).
//
// Precondition: mw.WriteStart() and mw.WriteMetadata() have been called.
// Postcondition: caller must call mw.Finalize().
func reindexFastCopy(mw *writer.MKVWriter, srcPath string, timecodeScale int64, fs *mkv.FS, progress mkv.ProgressFunc, totalBytes int64, videoTracks map[uint64]bool) error {
	raw, err := fs.DoOpen(srcPath)
	if err != nil {
		return fmt.Errorf("reindex open: %w", err)
	}
	defer raw.Close()

	// Wrap in a bufio.Reader for efficient sequential reads.
	r := bufio.NewReaderSize(raw, reindexBufSize)

	// Mirror BlockReader.init(): skip EBML header body, land on Segment data.
	ebmlHdr, ebmlHdrBytes, err := ebml.ReadElementHeader(r)
	if err != nil {
		return fmt.Errorf("reindex: EBML header: %w", err)
	}
	if ebmlHdr.ID != ebml.IDEBMLHeader {
		return fmt.Errorf("reindex: expected EBML header, got 0x%X", ebmlHdr.ID)
	}
	if _, err := io.CopyN(io.Discard, r, ebmlHdr.Size); err != nil {
		return fmt.Errorf("reindex: skip EBML header: %w", err)
	}

	segHdr, segHdrBytes, err := ebml.ReadElementHeader(r)
	if err != nil {
		return fmt.Errorf("reindex: Segment header: %w", err)
	}
	if segHdr.ID != mkv.IDSegment {
		return fmt.Errorf("reindex: expected Segment, got 0x%X", segHdr.ID)
	}
	// We do not need segEnd: unknown-size segment reads until EOF, known-size
	// segments also terminate naturally (their clusters fill them).

	// Track logical bytes consumed for progress reporting.
	consumed := int64(ebmlHdrBytes) + ebmlHdr.Size + int64(segHdrBytes)

	var (
		clusterBuf   []byte // reused; grown as needed
		firstCluster = true
	)

	for {
		h, hdrBytes, err := ebml.ReadElementHeader(r)
		if err != nil {
			if errors.Is(err, io.EOF) {
				return nil
			}
			return fmt.Errorf("reindex: top-level element: %w", err)
		}

		switch h.ID {
		case mkv.IDCluster:
			if h.Size < 0 {
				// Unknown-size cluster: can only fall back at the very first cluster.
				if firstCluster {
					return errUnknownSizeCluster
				}
				return fmt.Errorf("reindex: unknown-size cluster after first (streaming not supported)")
			}
			if h.Size > maxReindexClusterSize {
				return fmt.Errorf("reindex: cluster size %d exceeds limit (%d)", h.Size, maxReindexClusterSize)
			}
			firstCluster = false

			// Grow reusable buffer once.
			if int(h.Size) > len(clusterBuf) {
				clusterBuf = make([]byte, h.Size)
			}
			body := clusterBuf[:h.Size]
			if _, err := io.ReadFull(r, body); err != nil {
				return fmt.Errorf("reindex: read cluster body: %w", err)
			}
			consumed += int64(hdrBytes) + h.Size

			// Capture output offset BEFORE writing - this is the ClusterPos.
			outOff := mw.RelPos()

			// Scan cluster body to produce a cue entry.
			appendCueFromCluster(&mw.Cues, body, timecodeScale, outOff, videoTracks)

			// Write cluster header + verbatim body.
			if _, err := ebml.WriteElementID(mw.W, mkv.IDCluster); err != nil {
				return fmt.Errorf("reindex: write cluster ID: %w", err)
			}
			if _, err := ebml.WriteDataSize(mw.W, h.Size); err != nil {
				return fmt.Errorf("reindex: write cluster size: %w", err)
			}
			if _, err := mw.W.Write(body); err != nil {
				return fmt.Errorf("reindex: write cluster body: %w", err)
			}

			if progress != nil && totalBytes > 0 {
				progress(consumed, totalBytes)
			}

		default:
			// SeekHead, Cues, Void, Info, Tracks, Chapters, Attachments, Tags  -
			// all regenerated by WriteMetadata / Finalize; skip the source copy.
			if h.Size < 0 {
				return fmt.Errorf("reindex: unknown-size non-cluster element 0x%X", h.ID)
			}
			if _, err := io.CopyN(io.Discard, r, h.Size); err != nil {
				return fmt.Errorf("reindex: skip 0x%X: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size
		}
	}
}

// appendCueFromCluster scans the raw bytes of a cluster body to find the first
// keyframe and adds a CuePoint to cues. outOff is the Segment-data-relative byte
// offset of this cluster's element header (to store in CuePoint.ClusterPos).
// videoTracks, when non-empty, restricts the keyframe cue to VIDEO tracks:
// every audio block is flagged keyframe, so cueing "the first keyframe" of a
// mixed cluster would cue audio and never the real video keyframe. Clusters
// with no video keyframe fall back to the throttled first-block cue.
//
// Errors inside the scan are silently ignored (corrupt/truncated data): in the
// worst case we emit no cue for this cluster, which is safe.
func appendCueFromCluster(cues *[]mkv.CuePoint, body []byte, timecodeScale, outOff int64, videoTracks map[uint64]bool) {
	br := bytes.NewReader(body)

	var clusterTS int64
	// firstBlock* captures the very first block seen (used for audio-only cue).
	var firstBlockTC int64
	var firstBlockTrack uint64
	var firstBlockSeen bool

	for {
		h, _, err := ebml.ReadElementHeader(br)
		if err != nil {
			break // EOF or corrupt - stop scanning
		}

		switch h.ID {
		case mkv.IDTimestamp:
			v, err := ebml.ReadUint(br, h.Size)
			if err != nil {
				return
			}
			clusterTS = int64(v)

		case mkv.IDSimpleBlock:
			track, relTC, keyframe, err := readBlockHeader(br, h.Size)
			if err != nil {
				return
			}
			tc, err := reindexSafeTimecodeMs(clusterTS+int64(relTC), timecodeScale)
			if err != nil {
				return
			}
			if !firstBlockSeen {
				firstBlockSeen = true
				firstBlockTC = tc
				firstBlockTrack = track
			}
			if keyframe && (len(videoTracks) == 0 || videoTracks[track]) {
				// Found the first cueable keyframe - emit cue and exit.
				*cues = append(*cues, mkv.CuePoint{
					TimeMs:     tc,
					Track:      track,
					ClusterPos: outOff,
				})
				return
			}

		case mkv.IDBlockGroup:
			track, relTC, isKey, err := scanBlockGroup(br, h.Size)
			if err != nil {
				return
			}
			tc, err := reindexSafeTimecodeMs(clusterTS+int64(relTC), timecodeScale)
			if err != nil {
				return
			}
			if !firstBlockSeen {
				firstBlockSeen = true
				firstBlockTC = tc
				firstBlockTrack = track
			}
			if isKey && (len(videoTracks) == 0 || videoTracks[track]) {
				*cues = append(*cues, mkv.CuePoint{
					TimeMs:     tc,
					Track:      track,
					ClusterPos: outOff,
				})
				return
			}

		default:
			if h.Size < 0 {
				return // unknown-size child - stop scanning
			}
			if _, err := io.CopyN(io.Discard, br, h.Size); err != nil {
				return
			}
		}
	}

	// No video keyframe in this cluster. For a file WITH video, emit nothing: a
	// Cues index only needs entries at seekable video keyframes (real muxers cue
	// exactly those), and a cue landing mid-GOP on an audio block both misdirects
	// a seek and trips Validate's "seeking lands on audio" error - the two would
	// otherwise contradict, so a time-based repack (many keyframeless clusters)
	// could never pass its own reindex+validate. The audio fallback below is only
	// for a genuinely audio-only file, where there is no video keyframe to key on.
	if len(videoTracks) > 0 || !firstBlockSeen {
		return
	}
	lastCueTime := int64(-reindexCueMinGapMs - 1)
	if len(*cues) > 0 {
		lastCueTime = (*cues)[len(*cues)-1].TimeMs
	}
	if firstBlockTC-lastCueTime >= reindexCueMinGapMs {
		*cues = append(*cues, mkv.CuePoint{
			TimeMs:     firstBlockTC,
			Track:      firstBlockTrack,
			ClusterPos: outOff,
		})
	}
}

// readBlockHeader reads the fixed block header (track VINT + 2-byte relTC +
// 1-byte flags) and discards the remaining payload bytes.
// Returns (track, relTC, keyframe).
func readBlockHeader(r io.Reader, blockSize int64) (track uint64, relTC int16, keyframe bool, err error) {
	trackRaw, n, err := ebml.ReadDataSize(r)
	if err != nil {
		return 0, 0, false, err
	}
	track = uint64(trackRaw)
	consumed := int64(n)

	var tcBuf [2]byte
	if _, err := io.ReadFull(r, tcBuf[:]); err != nil {
		return 0, 0, false, err
	}
	relTC = int16(binary.BigEndian.Uint16(tcBuf[:]))
	consumed += 2

	var flagBuf [1]byte
	if _, err := io.ReadFull(r, flagBuf[:]); err != nil {
		return 0, 0, false, err
	}
	keyframe = flagBuf[0]&0x80 != 0
	consumed += 1

	remaining := blockSize - consumed
	if remaining > 0 {
		if _, err := io.CopyN(io.Discard, r, remaining); err != nil {
			return track, relTC, keyframe, err
		}
	}
	return track, relTC, keyframe, nil
}

// scanBlockGroup scans a BlockGroup's children to find the Block element and
// detect whether a ReferenceBlock is present (its presence means non-keyframe).
// Consumes exactly size bytes from r.
func scanBlockGroup(r io.Reader, size int64) (track uint64, relTC int16, isKeyframe bool, err error) {
	limit := &io.LimitedReader{R: r, N: size}
	var foundBlock bool
	var hasRef bool

	for {
		h, _, err := ebml.ReadElementHeader(limit)
		if err != nil {
			break
		}
		switch h.ID {
		case mkv.IDBlock:
			t, rt, _, e := readBlockHeader(limit, h.Size)
			if e != nil {
				// Drain and report error.
				io.CopyN(io.Discard, limit, limit.N) //nolint:errcheck
				return 0, 0, false, e
			}
			track = t
			relTC = rt
			foundBlock = true
		case mkv.IDReferenceBlock:
			hasRef = true
			io.CopyN(io.Discard, limit, h.Size) //nolint:errcheck
		default:
			if h.Size >= 0 {
				io.CopyN(io.Discard, limit, h.Size) //nolint:errcheck
			}
		}
	}
	// Drain any unconsumed bytes (e.g. unknown-size child stopped iteration).
	if limit.N > 0 {
		io.CopyN(io.Discard, limit, limit.N) //nolint:errcheck
	}
	if !foundBlock {
		return 0, 0, false, fmt.Errorf("BlockGroup without Block element")
	}
	return track, relTC, !hasRef, nil
}

// reindexSafeTimecodeMs converts raw timecode units to milliseconds,
// mirroring the unexported reader.safeTimecodeMs to avoid an import cycle.
func reindexSafeTimecodeMs(v, scale int64) (int64, error) {
	if scale != 0 && (v > math.MaxInt64/scale || v < math.MinInt64/scale) {
		return 0, fmt.Errorf("timecode overflow: %d * %d", v, scale)
	}
	return v * scale / 1_000_000, nil
}

// A cluster carries two hints that describe WHERE it sits, so a cluster copied
// to a different offset - or written after a different neighbour - takes them
// along as lies unless they are rewritten.
const (
	idClusterPosition = 0xA7 // the cluster's own Segment position
	idClusterPrevSize = 0xAB // the size of the cluster written before it
	idCRC32           = 0xBF
)

// clusterCRCSpan locates a cluster body's CRC-32: the offset of its 4-byte
// value and the end of the element. Per spec a CRC-32 is only trustworthy as
// the first child, and that is the only place it is honoured here. (-1, -1)
// when the body carries none.
func clusterCRCSpan(body []byte) (valOff, elemEnd int64) {
	h, n, err := ebml.ReadElementHeader(bytes.NewReader(body))
	if err != nil || h.ID != idCRC32 || h.Size != 4 || int64(n)+4 > int64(len(body)) {
		return -1, -1
	}
	return int64(n), int64(n) + 4
}

// resealClusterCRC recomputes a rewritten cluster's CRC-32 over its (patched)
// bytes, little-endian, and returns the patch that lands it - nil when the body
// has no CRC-32 or the value did not move. origCRC must be the CRC bytes as
// they were in the SOURCE, so the rollback delta can undo the patch.
func resealClusterCRC(body []byte, valOff, elemEnd int64, origCRC []byte) *retimePatch {
	if valOff < 0 {
		return nil
	}
	newCRC := sealClusterCRC(body)
	if bytes.Equal(origCRC, newCRC) {
		return nil
	}
	return &retimePatch{off: valOff, orig: origCRC, repl: newCRC}
}

// sealClusterCRC recomputes a cluster body's CRC-32 in place (no-op when it
// carries none) and returns the value it wrote.
func sealClusterCRC(body []byte) []byte {
	valOff, elemEnd := clusterCRCSpan(body)
	if valOff < 0 {
		return nil
	}
	newCRC := make([]byte, 4)
	binary.LittleEndian.PutUint32(newCRC, crc32.ChecksumIEEE(body[elemEnd:]))
	copy(body[valOff:valOff+4], newCRC)
	return newCRC
}

// retargetClusterPatches rewrites the position hints a RELOCATED cluster
// carries: Position (its own Segment position) and PrevSize (the size of the
// cluster before it, -1 when there is none). Both are optional, and a reader
// that trusts a stale one seeks to the wrong place - worse than not having it.
//
// The patches never change the element's span, so the cluster's own size stays
// valid and the rollback delta keeps tiling the body: a value that still fits
// the bytes it had is written into them (an EBML uint may carry leading zeros),
// and one that no longer fits - or that no longer exists, as for the first
// cluster's PrevSize - retires the element to a Void of the same span.
func retargetClusterPatches(body []byte, segPos, prevSize int64) []retimePatch {
	var out []retimePatch
	br := bytes.NewReader(body)
	total := int64(len(body))
	for br.Len() > 0 {
		start := total - int64(br.Len())
		h, n, err := ebml.ReadElementHeader(br)
		if err != nil || h.Size < 0 || h.Size > int64(br.Len()) {
			return out // an unparseable tail is left exactly as it was
		}
		switch h.ID {
		case idClusterPosition:
			out = appendHintPatch(out, body, start, int64(n), h.Size, segPos)
		case idClusterPrevSize:
			out = appendHintPatch(out, body, start, int64(n), h.Size, prevSize)
		}
		if _, err := br.Seek(h.Size, io.SeekCurrent); err != nil {
			return out
		}
	}
	return out
}

// appendHintPatch restates one uint hint in the bytes it already occupies, or
// voids the whole element when the new value cannot be said there.
func appendHintPatch(out []retimePatch, body []byte, elemStart, hdrLen, valLen, v int64) []retimePatch {
	span := hdrLen + valLen
	orig := append([]byte(nil), body[elemStart:elemStart+span]...)
	repl := append([]byte(nil), orig...)

	if v >= 0 && (valLen >= 8 || v>>(8*uint(valLen)) == 0) {
		for i := valLen - 1; i >= 0; i-- { // fits: same element, true value
			repl[hdrLen+i] = byte(v)
			v >>= 8
		}
	} else {
		hdr, err := writer.VoidHeader(int(span))
		if err != nil {
			return out // cannot be voided either: leave the source bytes alone
		}
		repl = make([]byte, span)
		copy(repl, hdr)
	}
	if bytes.Equal(orig, repl) {
		return out
	}
	return append(out, retimePatch{off: elemStart, orig: orig, repl: repl})
}

// clusterHasPositionHints reports whether a cluster body carries a Position or
// PrevSize element - the two the relocation rewrites.
func clusterHasPositionHints(body []byte) bool {
	br := bytes.NewReader(body)
	for br.Len() > 0 {
		h, _, err := ebml.ReadElementHeader(br)
		if err != nil || h.Size < 0 || h.Size > int64(br.Len()) {
			return false
		}
		if h.ID == idClusterPosition || h.ID == idClusterPrevSize {
			return true
		}
		if _, err := br.Seek(h.Size, io.SeekCurrent); err != nil {
			return false
		}
	}
	return false
}

// clusterHasCRC reports whether a cluster body opens with a CRC-32.
func clusterHasCRC(body []byte) bool {
	valOff, _ := clusterCRCSpan(body)
	return valOff >= 0
}

func applyPatches(body []byte, patches []retimePatch) {
	for _, p := range patches {
		copy(body[p.off:p.off+int64(len(p.repl))], p.repl)
	}
}

// writeClusterVerbatim writes one cluster (header + body) to mw, appends a cue
// point, and reports progress. body must be the complete cluster body already
// read from the source. outOff is mw.RelPos() captured before this call.
func writeClusterVerbatim(mw *writer.MKVWriter, body []byte, bodySize int64, timecodeScale, outOff int64, videoTracks map[uint64]bool) error {
	appendCueFromCluster(&mw.Cues, body, timecodeScale, outOff, videoTracks)
	if _, err := ebml.WriteElementID(mw.W, mkv.IDCluster); err != nil {
		return fmt.Errorf("reindex: write cluster ID: %w", err)
	}
	if _, err := ebml.WriteDataSize(mw.W, bodySize); err != nil {
		return fmt.Errorf("reindex: write cluster size: %w", err)
	}
	if _, err := mw.W.Write(body); err != nil {
		return fmt.Errorf("reindex: write cluster body: %w", err)
	}
	return nil
}

// Reindex produces a byte-faithful copy of srcPath at dstPath, replacing only
// the seek index (SeekHead + Cues). Every other element - Info, Tracks, Tags,
// Chapters, Attachments, cluster payloads - is copied verbatim, byte for byte,
// without re-serialisation. The source's EBML header is also copied verbatim so
// that the DocType (e.g. "webm") is preserved.
//
// Use this instead of EditMetadata when the only goal is to add a seek index to
// a file that lacks one or has a stale one, and fidelity to the original
// metadata encoding matters.
//
// The result is always re-opened afterwards and its Cues index checked against
// the cues built during the copy (light verification, a few milliseconds).
// When Options.DeepVerify is set, Reindex additionally runs a full-read
// Validate on dstPath and a byte-level payload comparison (CompareBlocks)
// against srcPath, proving the copy verbatim rather than merely well-formed.
// A failed verification returns an error and dstPath is left as written (the
// caller decides whether to discard it) - see ReindexReplace for a variant
// that only replaces the original after every check has passed. A
// file-only-permission variant with no output copy (ReindexInPlace) exists
// separately.
//
// Trailing junk is tolerated without any option: bytes past the DECLARED
// Segment end that neither parse as an element nor carry any trace of a
// Cluster (a bounded scan looks for the Cluster ID itself, so even a cluster
// CUT mid-write keeps the strict refusal) are dropped from the output and
// reported through Options.OnSkip - a few surplus bytes at EOF must not make
// a 2 GB file unrepairable, and every reader already stops at the declared
// end. Corruption INSIDE the declared Segment still aborts (wrapping
// ErrCorruptSource); that is what Options.Resync is for.
//
// With Options.Resync set, a corrupted region in the cluster stream no longer
// aborts the copy: the walk scans forward (bounded, 64 MiB) for the next
// structurally valid Cluster and resumes, dropping the skipped bytes from the
// output and reporting each dropped span through Options.OnSkip. The repair
// is refused when no valid Cluster is found within the scan window, when no
// cluster survives, or when more than half of the walked payload would be
// dropped. Under Resync the DeepVerify byte-comparison against the source
// only runs when nothing was skipped (a source that lost ranges cannot be
// walked for a verbatim proof); the full-read Validate of the output always
// runs.
func Reindex(ctx context.Context, srcPath, dstPath string, opts ...mkv.Options) error {
	fs := mkv.FSFrom(opts)

	if mkv.ResyncFrom(opts) {
		return reindexResync(ctx, srcPath, dstPath, fs, opts)
	}

	var rb *rollbackBuilder
	if mkv.RollbackSinkFrom(opts) != nil {
		rb = newSpoolingRollbackBuilder(fs, dstPath+".rbspool.tmp")
		defer rb.cleanup()
	}

	cues, timecodeScale, dropped, err := reindexCopy(ctx, srcPath, dstPath, fs, mkv.ProgressFrom(opts), rb, nil)
	if err != nil {
		return err
	}

	if err := verifyReindexedCues(ctx, dstPath, fs, cues, timecodeScale); err != nil {
		return err
	}

	if mkv.DeepVerifyFrom(opts) {
		before := preValidate(ctx, srcPath, fs)
		if err := deepVerifyValidate(ctx, dstPath, fs, before, mkv.StrictVerifyFrom(opts), mkv.OnPreexistingFrom(opts)); err != nil {
			return err
		}
		// Dropped trailing junk does not disturb the verbatim proof: it lies
		// past the declared Segment end, where the block walk never reads.
		if err := deepVerifyVerbatim(ctx, srcPath, dstPath, fs); err != nil {
			return err
		}
	}

	if err := emitRollbackEntry(ctx, rb, srcPath, dstPath, fs, opts); err != nil {
		return err
	}
	if onSkip := mkv.OnSkipFrom(opts); onSkip != nil {
		for _, r := range dropped {
			onSkip(r)
		}
	}
	return nil
}

// ErrCorruptSource is wrapped into the strict-walk refusals of Reindex and
// the retime operations when the source is not what the strict walk requires
// of a sealed file: an element header that will not decode, a malformed
// cluster child, a block that does not follow its cluster's Timestamp, or an
// unknown-size element inside a sized Segment (a streamed leftover the
// strict engines cannot bound). Permanent for the file as it is: retrying
// the same call cannot succeed; repair the file first (Reindex with
// Options.Resync, or Salvage) and then retry. errors.Is-able.
var ErrCorruptSource = errors.New("the source is structurally corrupt")

// clusterMutator lets a rewrite transform each cluster body in place before
// it is written (RetimeTracksReplace patches block timecodes and cluster
// CRCs this way). It returns the byte-range patches it applied, sorted by
// offset, each carrying the ORIGINAL bytes - the rollback delta needs them
// to keep reconstructing the source. body offsets are body-relative.
type clusterMutator func(body []byte) ([]retimePatch, error)

// reindexCopy performs the actual byte-faithful copy from srcPath to dstPath,
// rebuilding only the seek index (SeekHead + Cues). It returns the cue points
// built during the walk and the timecode scale used to derive them, so the
// caller can verify the result against them. See Reindex for the full contract.
// A non-nil rb collects the inverse rollback delta along the way: COPY ops for
// the verbatim bodies, literals for the re-encoded headers and dropped index
// elements. A non-nil mutate transforms each cluster body before writing (the
// delta then splits its COPY runs around the mutated spans).
//
// Trailing junk - bytes past the declared Segment end that neither parse as
// an element nor carry any trace of a Cluster - is dropped from the output
// and returned in dropped (at most one range, running to EOF), never an
// error: surplus bytes must not make an otherwise-healthy file unrepairable.
// The caller reports the range through Options.OnSkip once its own checks
// pass.
func reindexCopy(ctx context.Context, srcPath, dstPath string, fs *mkv.FS, progress mkv.ProgressFunc, rb *rollbackBuilder, mutate clusterMutator) (cues []mkv.CuePoint, timecodeScale int64, dropped []mkv.DamagedRange, err error) {
	// A cheap head-only read of the track list, so the rebuilt cues key on
	// VIDEO keyframes (every audio block is flagged keyframe).
	var videoTracks map[uint64]bool
	if meta, merr := reader.OpenMetaWithFS(ctx, srcPath, fs); merr == nil {
		videoTracks = videoTrackSet(meta.Tracks)
	}

	raw, err := fs.DoOpen(srcPath)
	if err != nil {
		return nil, 0, nil, fmt.Errorf("reindex open src: %w", err)
	}
	defer raw.Close()

	out, err := fs.DoCreate(dstPath)
	if err != nil {
		return nil, 0, nil, fmt.Errorf("reindex create dst: %w", err)
	}
	defer closeWithErr(out, &err)

	r := bufio.NewReaderSize(raw, reindexBufSize)
	mw := writer.NewMKVWriter(out)

	// ── EBML header + Segment open ────────────────────────────────────────────
	ebmlBytes, err := copyEBMLHeaderVerbatim(r, out, rb)
	if err != nil {
		return nil, 0, nil, fmt.Errorf("reindex: %w", err)
	}
	segBytes, segDeclared, err := beginSegmentRewrite(r, out, mw, rb)
	if err != nil {
		return nil, 0, nil, fmt.Errorf("reindex: %w", err)
	}

	// ── Walk source Segment elements ──────────────────────────────────────────
	var (
		clusterBuf []byte
		// prevClusterSize is the size of the cluster written before the current
		// one, for its PrevSize hint. -1 until one has been written: the first
		// cluster of the output has no predecessor, whatever the source said.
		prevClusterSize = int64(-1)
		firstCluster    = true
		// consumed is the absolute source offset of the next element to read.
		consumed = ebmlBytes + segBytes
	)
	timecodeScale = 1_000_000 // default; overridden when Info is copied

	var fileSize int64
	if stat, _ := fs.DoStat(srcPath); stat != nil {
		fileSize = stat.Size()
	}
	// segEnd is the declared absolute end of the Segment; -1 when the size is
	// unknown (streamed) or the file size is unavailable. Bytes at or past it
	// are candidates for the trailing-junk drop below, never inside it.
	segEnd := int64(-1)
	if segDeclared >= 0 && fileSize > 0 {
		segEnd = consumed + segDeclared
	}

	// dropTrailingJunk classifies the bytes at [start, EOF) - already known to
	// sit at or past the declared Segment end and not to be a real element -
	// and either records them as dropped junk (rollback literal included, so
	// the delta keeps reconstructing the source byte for byte) or returns the
	// strict refusal when they are not provably junk.
	dropTrailingJunk := func(start int64, cause error) error {
		junk, jerr := reindexTrailingJunk(raw, start, fileSize, lastCueMs(mw.Cues), cause)
		if jerr != nil {
			return jerr
		}
		if rb != nil {
			rb.literalFrom(raw, junk.StartOffset, junk.EndOffset-junk.StartOffset)
		}
		dropped = append(dropped, junk)
		return nil
	}

	for {
		if ctx.Err() != nil {
			return nil, 0, nil, ctx.Err()
		}
		elemStart := consumed
		h, hdrBytes, err := ebml.ReadElementHeader(r)
		if err != nil {
			if errors.Is(err, io.EOF) {
				// A bare io.EOF with bytes still on disk past the declared end
				// is NOT a clean end: the header read consumed a complete
				// element ID and hit EOF before its size (a torn write's exact
				// shape). Breaking here would drop those bytes invisibly - no
				// report, and a rollback delta missing them could never
				// reconstruct the source.
				if segEnd >= 0 && elemStart >= segEnd && elemStart < fileSize {
					cause := fmt.Errorf("trailing bytes at %d end mid-element-header", elemStart)
					if jerr := dropTrailingJunk(elemStart, cause); jerr != nil {
						return nil, 0, nil, jerr
					}
				}
				break
			}
			if segEnd >= 0 && elemStart >= segEnd {
				if jerr := dropTrailingJunk(elemStart, err); jerr != nil {
					return nil, 0, nil, jerr
				}
				break
			}
			return nil, 0, nil, fmt.Errorf("reindex: top-level element: %w (a corrupted region can be skipped with Options.Resync / --resync): %w", err, ErrCorruptSource)
		}
		// Junk can also masquerade as an element header: past the declared
		// Segment end, an element that has no bounded size or does not fit the
		// remaining file cannot be real, and takes the same trailing-junk path
		// (an element that parses AND fits is real and is copied as usual - a
		// Segment whose declared size undershoots its content keeps working).
		if segEnd >= 0 && elemStart >= segEnd &&
			(h.Size < 0 || elemStart+int64(hdrBytes)+h.Size > fileSize) {
			cause := fmt.Errorf("element 0x%X at %d overruns the end of the file", h.ID, elemStart)
			if jerr := dropTrailingJunk(elemStart, cause); jerr != nil {
				return nil, 0, nil, jerr
			}
			break
		}

		switch h.ID {
		case mkv.IDSeekHead, mkv.IDCues, mkv.IDVoid:
			// Drop old index elements - they will be rebuilt by Finalize.
			if h.Size < 0 {
				return nil, 0, nil, fmt.Errorf("reindex: unknown-size index element 0x%X", h.ID)
			}
			litDst := io.Discard
			if rb != nil {
				// The output has no trace of these: whole element to literals.
				rb.literalHeader(h, hdrBytes)
				litDst = rb.literalWriter(h.Size)
			}
			if _, err := io.CopyN(litDst, r, h.Size); err != nil {
				return nil, 0, nil, fmt.Errorf("reindex: skip 0x%X: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size

		case mkv.IDInfo, mkv.IDTracks, mkv.IDTags, mkv.IDChapters, mkv.IDAttachments:
			// Copy verbatim; record position so Finalize's SeekHead points here.
			if h.Size < 0 {
				return nil, 0, nil, fmt.Errorf("reindex: unknown-size metadata element 0x%X", h.ID)
			}
			if h.Size > maxReindexClusterSize {
				return nil, 0, nil, fmt.Errorf("reindex: metadata element 0x%X size %d exceeds limit (%d bytes)", h.ID, h.Size, maxReindexClusterSize)
			}
			// Buffer the body so we can (a) scan Info for timecodeScale and
			// (b) write it out verbatim in one step.
			metaBuf := make([]byte, h.Size)
			if _, err := io.ReadFull(r, metaBuf); err != nil {
				return nil, 0, nil, fmt.Errorf("reindex: read 0x%X body: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size
			// Extract timecodeScale from Info before writing.
			if h.ID == mkv.IDInfo {
				if ts := reindexScanTimecodeScale(metaBuf); ts > 0 {
					timecodeScale = ts
				}
				mw.TimecodeScale = timecodeScale
			}
			if rb != nil {
				rb.literalHeader(h, hdrBytes)
			}
			if err := writeMetaElementVerbatim(mw, out, h, metaBuf); err != nil {
				return nil, 0, nil, fmt.Errorf("reindex: %w", err)
			}
			if rb != nil {
				// The body was just written verbatim, ending at the current
				// output position: that position minus the body length is the
				// COPY source, with no assumption about the header encoding.
				after, serr := out.Seek(0, io.SeekCurrent)
				if serr != nil {
					return nil, 0, nil, fmt.Errorf("reindex: rollback offset: %w", serr)
				}
				rb.copyRun(after-h.Size, metaBuf)
			}

		case mkv.IDCluster:
			if h.Size < 0 {
				if firstCluster {
					return nil, 0, nil, fmt.Errorf("reindex: unknown-size cluster (streaming not supported)")
				}
				return nil, 0, nil, fmt.Errorf("reindex: unknown-size cluster after first")
			}
			if h.Size > maxReindexClusterSize {
				return nil, 0, nil, fmt.Errorf("reindex: cluster size %d exceeds limit (%d)", h.Size, maxReindexClusterSize)
			}
			firstCluster = false

			if int(h.Size) > len(clusterBuf) {
				clusterBuf = make([]byte, h.Size)
			}
			body := clusterBuf[:h.Size]
			if _, err := io.ReadFull(r, body); err != nil {
				return nil, 0, nil, fmt.Errorf("reindex: read cluster body: %w", err)
			}
			consumed += int64(hdrBytes) + h.Size

			outOff := mw.RelPos()
			// The cluster lands at a different Segment position than it had (the
			// head region is rebuilt), so its Position/PrevSize hints must be
			// restated before anything else reads or checksums the body.
			crcOff, crcEnd := clusterCRCSpan(body)
			var origCRC []byte
			if crcOff >= 0 {
				origCRC = append([]byte(nil), body[crcOff:crcOff+4]...)
			}
			patches := retargetClusterPatches(body, outOff, prevClusterSize)
			applyPatches(body, patches)

			if mutate != nil {
				mp, merr := mutate(body)
				if merr != nil {
					return nil, 0, nil, merr
				}
				patches = append(patches, mp...)
			}
			// One CRC-32 reseal for the lot, over the final bytes: a mutator may
			// have patched it over its own changes only, and the retarget above
			// landed after that.
			if len(patches) > 0 && crcOff >= 0 {
				kept := patches[:0]
				for _, p := range patches {
					if p.off != crcOff {
						kept = append(kept, p)
					}
				}
				patches = kept
				if p := resealClusterCRC(body, crcOff, crcEnd, origCRC); p != nil {
					patches = append(patches, *p)
				}
			}
			sort.Slice(patches, func(i, j int) bool { return patches[i].off < patches[j].off })

			if rb != nil {
				rb.literalHeader(h, hdrBytes)
			}
			if err := writeClusterVerbatim(mw, body, h.Size, timecodeScale, outOff, videoTracks); err != nil {
				return nil, 0, nil, err
			}
			prevClusterSize = mw.RelPos() - outOff
			if rb != nil {
				after, serr := out.Seek(0, io.SeekCurrent)
				if serr != nil {
					return nil, 0, nil, fmt.Errorf("reindex: rollback offset: %w", serr)
				}
				bodyDst := after - h.Size
				// The written body may differ from the source at the mutated
				// spans: the delta alternates COPY runs (unchanged bytes) and
				// literals carrying the ORIGINAL bytes of each span.
				cur := int64(0)
				for _, p := range patches {
					if p.off > cur {
						rb.copyRun(bodyDst+cur, body[cur:p.off])
					}
					rb.literal(p.orig)
					cur = p.off + int64(len(p.orig))
				}
				if cur < h.Size {
					rb.copyRun(bodyDst+cur, body[cur:])
				}
			}

			if progress != nil && fileSize > 0 {
				progress(consumed, fileSize)
			}

		default:
			// Unknown top-level element: copy verbatim to preserve any extensions.
			if h.Size < 0 {
				return nil, 0, nil, fmt.Errorf("reindex: unknown-size element 0x%X", h.ID)
			}
			if _, err := ebml.WriteElementID(out, h.ID); err != nil {
				return nil, 0, nil, fmt.Errorf("reindex: write unknown 0x%X ID: %w", h.ID, err)
			}
			if _, err := ebml.WriteDataSize(out, h.Size); err != nil {
				return nil, 0, nil, fmt.Errorf("reindex: write unknown 0x%X size: %w", h.ID, err)
			}
			bodyDst := io.Writer(out)
			if rb != nil {
				rb.literalHeader(h, hdrBytes)
				bodyOff, serr := out.Seek(0, io.SeekCurrent)
				if serr != nil {
					return nil, 0, nil, fmt.Errorf("reindex: rollback offset: %w", serr)
				}
				bodyDst = io.MultiWriter(out, rb.copyRunStreamed(bodyOff, h.Size))
			}
			if _, err := io.CopyN(bodyDst, r, h.Size); err != nil {
				return nil, 0, nil, fmt.Errorf("reindex: copy unknown 0x%X body: %w", h.ID, err)
			}
			consumed += int64(hdrBytes) + h.Size
		}
	}

	if err := mw.Finalize(); err != nil {
		return nil, 0, nil, err
	}
	return mw.Cues, timecodeScale, dropped, nil
}

// reindexTrailingJunk decides whether the bytes at [start, fileSize) - which
// begin at or past the declared Segment end and do not parse as an element -
// are droppable trailing junk. Junk must prove itself: a bounded scan
// (salvageResyncCap, the window every resync scan uses) must reach EOF
// without finding even a TRACE of a Cluster - the 4-byte Cluster ID, not a
// structurally valid Cluster. A complete Cluster past the failure means real
// media behind an undershooting Segment size, and a Cluster ID whose element
// was cut mid-write (a torn download's tail) is real media too, invisible to
// any structural validation precisely because it is incomplete; a strict
// walk must drop neither. Anything unproven keeps the strict refusal
// carrying cause. lastMs stamps the range with the last indexed time, the
// closest honest approximation for bytes at the very end of the file.
func reindexTrailingJunk(raw io.ReadSeeker, start, fileSize, lastMs int64, cause error) (mkv.DamagedRange, error) {
	strict := fmt.Errorf("reindex: top-level element: %w (a corrupted region can be skipped with Options.Resync / --resync): %w", cause, ErrCorruptSource)
	if start+salvageResyncCap < fileSize {
		// Junk longer than the scan window cannot be proven junk.
		return mkv.DamagedRange{}, strict
	}
	found, err := regionContainsClusterMagic(raw, start, fileSize)
	if err != nil {
		return mkv.DamagedRange{}, fmt.Errorf("reindex: trailing-bytes scan: %w", err)
	}
	if found {
		return mkv.DamagedRange{}, strict
	}
	return mkv.DamagedRange{
		StartOffset: start, EndOffset: fileSize,
		ApproxStartMs: lastMs, ApproxEndMs: lastMs,
	}, nil
}

// regionContainsClusterMagic reports whether [start, end) of raw contains the
// 4-byte Cluster element ID anywhere, chunked with a 3-byte overlap so a
// pattern straddling two reads is still seen.
func regionContainsClusterMagic(raw io.ReadSeeker, start, end int64) (bool, error) {
	magic := []byte{0x1F, 0x43, 0xB6, 0x75}
	if _, err := raw.Seek(start, io.SeekStart); err != nil {
		return false, err
	}
	const chunkSize = 64 << 10
	buf := make([]byte, chunkSize)
	carry := 0 // trailing bytes of the previous chunk kept in front of buf
	for pos := start; pos < end; {
		want := min(chunkSize-carry, int(end-pos))
		n, err := io.ReadFull(raw, buf[carry:carry+want])
		if n > 0 {
			if bytes.Contains(buf[:carry+n], magic) {
				return true, nil
			}
			pos += int64(n)
			carry = copy(buf, tailBytes(buf[:carry+n], len(magic)-1))
		}
		if err != nil {
			// The file ended earlier than the caller's bound: everything that
			// exists has been scanned.
			if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
				return false, nil
			}
			return false, err
		}
	}
	return false, nil
}

// tailBytes returns the last n bytes of b (all of b when shorter).
func tailBytes(b []byte, n int) []byte {
	if len(b) <= n {
		return b
	}
	return b[len(b)-n:]
}

// lastCueMs is the time of the last cue built so far, 0 when none exists yet.
func lastCueMs(cues []mkv.CuePoint) int64 {
	if len(cues) == 0 {
		return 0
	}
	return cues[len(cues)-1].TimeMs
}

// copyEBMLHeaderVerbatim reads the source EBML header from r and writes it byte
// for byte to out, so the DocType (e.g. "webm") is preserved across a rewrite.
// Returns the source bytes consumed. Shared by reindexCopy and salvageCopy.
func copyEBMLHeaderVerbatim(r io.Reader, out io.Writer, rb *rollbackBuilder) (int64, error) {
	ebmlHdr, hdrBytes, err := ebml.ReadElementHeader(r)
	if err != nil {
		return 0, fmt.Errorf("read EBML header: %w", err)
	}
	if ebmlHdr.ID != ebml.IDEBMLHeader {
		return 0, fmt.Errorf("expected EBML header, got 0x%X", ebmlHdr.ID)
	}
	if ebmlHdr.Size < 0 {
		return 0, fmt.Errorf("EBML header has unknown size")
	}
	if ebmlHdr.Size > maxReindexClusterSize {
		return 0, fmt.Errorf("EBML header size %d exceeds limit (%d bytes)", ebmlHdr.Size, maxReindexClusterSize)
	}
	ebmlBody := make([]byte, ebmlHdr.Size)
	if _, err := io.ReadFull(r, ebmlBody); err != nil {
		return 0, fmt.Errorf("read EBML body: %w", err)
	}
	if rb != nil {
		rb.literalHeader(ebmlHdr, hdrBytes)
		rb.literal(ebmlBody)
	}
	// Write the EBML element verbatim: ID header + body.
	if _, err := ebml.WriteElementID(out, ebmlHdr.ID); err != nil {
		return 0, fmt.Errorf("write EBML ID: %w", err)
	}
	if _, err := ebml.WriteDataSize(out, ebmlHdr.Size); err != nil {
		return 0, fmt.Errorf("write EBML size: %w", err)
	}
	if _, err := out.Write(ebmlBody); err != nil {
		return 0, fmt.Errorf("write EBML body: %w", err)
	}
	return int64(hdrBytes) + ebmlHdr.Size, nil
}

// beginSegmentRewrite reads the source Segment header from r and opens the
// output Segment the way every index rewrite does: unknown size, a Void
// placeholder where Finalize will patch the rebuilt SeekHead, and the
// writer's position bookkeeping primed. Returns the source bytes consumed
// (the Segment header itself) and the source's declared Segment size (-1
// when unknown/streamed), so the walk can tell bytes past the declared end
// from bytes inside it. Shared by reindexCopy and salvageCopy.
func beginSegmentRewrite(r io.Reader, out io.WriteSeeker, mw *writer.MKVWriter, rb *rollbackBuilder) (int64, int64, error) {
	segHdr, segHdrBytes, err := ebml.ReadElementHeader(r)
	if err != nil {
		return 0, 0, fmt.Errorf("read Segment header: %w", err)
	}
	if segHdr.ID != mkv.IDSegment {
		return 0, 0, fmt.Errorf("expected Segment, got 0x%X", segHdr.ID)
	}
	if rb != nil {
		// The output Segment header is re-encoded (unknown size): the source
		// one is delta material, whatever size it declared.
		rb.literalHeader(segHdr, segHdrBytes)
	}
	if _, err := ebml.WriteElementID(out, mkv.IDSegment); err != nil {
		return 0, 0, fmt.Errorf("write Segment ID: %w", err)
	}
	if _, err := ebml.WriteDataSize(out, -1); err != nil {
		return 0, 0, fmt.Errorf("write Segment size: %w", err)
	}
	segDataStart, err := out.Seek(0, io.SeekCurrent)
	if err != nil {
		return 0, 0, fmt.Errorf("seek Segment data start: %w", err)
	}
	mw.SegDataStart = segDataStart
	mw.SeekHeadPos = 0
	if err := writer.WriteVoid(out, writer.SeekHeadReserve); err != nil {
		return 0, 0, fmt.Errorf("write SeekHead placeholder: %w", err)
	}
	return int64(segHdrBytes), segHdr.Size, nil
}

// writeMetaElementVerbatim records the metadata element's output position on
// mw (so Finalize's SeekHead points at it) and writes the element verbatim.
// Shared by reindexCopy and salvageCopy; the caller extracts TimecodeScale
// from an Info body before calling.
func writeMetaElementVerbatim(mw *writer.MKVWriter, out io.Writer, h ebml.ElementHeader, body []byte) error {
	pos := mw.RelPos()
	switch h.ID {
	case mkv.IDInfo:
		mw.InfoPos = pos
	case mkv.IDTracks:
		mw.TracksPos = pos
	case mkv.IDTags:
		mw.TagsPos = pos
	case mkv.IDChapters:
		mw.ChaptersPos = pos
	case mkv.IDAttachments:
		mw.AttachPos = pos
	}
	if _, err := ebml.WriteElementID(out, h.ID); err != nil {
		return fmt.Errorf("write 0x%X ID: %w", h.ID, err)
	}
	if _, err := ebml.WriteDataSize(out, h.Size); err != nil {
		return fmt.Errorf("write 0x%X size: %w", h.ID, err)
	}
	if _, err := out.Write(body); err != nil {
		return fmt.Errorf("write 0x%X body: %w", h.ID, err)
	}
	return nil
}

// reindexScanTimecodeScale scans the raw bytes of an Info element body for the
// IDTimecodeScale child element and returns its value. Returns 0 if not found
// or on any parse error (caller keeps the default 1_000_000).
func reindexScanTimecodeScale(body []byte) int64 {
	br := bytes.NewReader(body)
	for {
		h, _, err := ebml.ReadElementHeader(br)
		if err != nil {
			return 0
		}
		if h.ID == mkv.IDTimecodeScale {
			v, err := ebml.ReadUint(br, h.Size)
			if err != nil {
				return 0
			}
			return int64(v)
		}
		if h.Size < 0 {
			return 0
		}
		if _, err := io.CopyN(io.Discard, br, h.Size); err != nil {
			return 0
		}
	}
}
